### ISSUE TITLE
(Enhancement) Hiding unobtainable items

### ISSUE THREAD

**Issue by pwigary** [Darkhax-Minecraft/Enchantment-Descriptions#54]
Let items which "hided" on JEI to be not able to display on the JEI "Compactible items" tab as well.(For survival). 

![2021-04-12_10 52 00](https://user-images.githubusercontent.com/82340024/114334518-483b5f80-9b7d-11eb-8be1-8be9d7d77999.png)

**Comment by Darkhax** [comment]
Thanks for the bug report, this should now be fixed in the latest version [7.0.6](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3273309).

**Comment by pwigary** [comment]
Wasn't know it was a bug, but the latest version causes the game to crash when loading

[crash-2021-04-12_22.11.40-client.txt](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/6297381/crash-2021-04-12_22.11.40-client.txt)

[modlist-12-04-2021_22.19.59.txt](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/6297394/modlist-12-04-2021_22.19.59.txt)

**Comment by Darkhax** [comment]
That crash log seems unrelated to this mod and I am able to get it loading just fine in several modpacks. Did you upload the right crash log and mod list? Im not seeing EnchantmentDescriptions in the mod list.

**Comment by pwigary** [comment]
Okay, I loaded in the game somehow, but I can still see the Jason's sword I hide from JEI on the "compactible item" tab.

https://ibb.co/Tctw24m
https://ibb.co/nQwSdF5

But when I hide others they works..
